packages:
  github.com/Blackdeer1524/GraphDB/src/pkg/common:
    config:
      dir: "{{.InterfaceDir}}"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      ITxnLoggerWithContext:
      ITxnLogger:

  github.com/Blackdeer1524/GraphDB/src/txns:
    config:
      dir: "{{.InterfaceDir}}"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      ILockManager:

  github.com/Blackdeer1524/GraphDB/src/storage:
    config:
      dir: "{{.InterfaceDir}}"
      outpkg: "{{.PackageName}}"
      inpackage: true
    interfaces:
      Engine:
      SystemCatalog:
      Index:
